workers_dev = true
name = "mob-vibe-coding"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Mob Vibe Coding"
COOKIE_DOMAIN = "mob-vibe-coding.tywen-kelly.workers.dev"

[env.local.vars]
COOKIE_DOMAIN = "localhost"

[[d1_databases]]
binding = "DB"
database_name = "mob-vibe-coding-db"
database_id = "2e4d0be3-cb47-468e-a3af-fdcb98ed282e"
migrations_dir = "drizzle"

[observability]
enabled = true
head_sampling_rate = 1
