workers_dev = true
name = "my-worker"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "better-websim-db"
database_id = "a5c1bdc8-33c2-45eb-af7e-7efb0636df2c"
migrations_dir = "drizzle"
